### PR TITLE
Fix max block count

### LINKED ISSUE #11: Do not support device larger than 2TB
The block size default is 512.
When device larger than 2TB, `BlockCount` will overflow.

https://github.com/cloudbase/wnbd/blob/75ddd4832908153808a60723d38e988a6bfa41f0/driver/scsi_operation.c#L59

### PR DESCRIPTION
**Pull request by CzBiX**
Fix #11.

### CODE REVIEW

File: driver/scsi_operation.c [hunk 1]
```diff
@@ -30,55 +30,85 @@ UCHAR
...
         {
         if (sizeof(READ_CAPACITY_DATA) > DataTransferLength) {
             goto Exit;
         }
+
         PREAD_CAPACITY_DATA ReadCapacityData = DataBuffer;
-        REVERSE_BYTES_4(&ReadCapacityData->LogicalBlockAddress, &BlockCount);
+
+        if (maxLba >= MAXULONG) {
+            ReadCapacityData->LogicalBlockAddress = MAXULONG;
```
Comment (petrutlucian94) [inline driver/scsi_operation.c:64]: 0xffffffff will be the same regardless of endianness, so this looks good.

File: driver/scsi_operation.c [hunk 2]
```diff
@@ -30,55 +30,85 @@ UCHAR
...
     ULONG DataTransferLength = SrbGetDataTransferLength(Srb);
-    UCHAR SrbStatus = SRB_STATUS_DATA_OVERRUN;
+    UCHAR SrbStatus = SRB_STATUS_INVALID_REQUEST;
 
-    if (0 == DataBuffer) {
+    if (0 == DataBuffer || 0 == BlockCount) {
+        SrbStatus = SRB_STATUS_INTERNAL_ERROR;
         goto Exit;
     }
+    UINT64 maxLba = BlockCount - 1;
```
Comment (petrutlucian94) [inline driver/scsi_operation.c:49]: Good catch.

File: driver/scsi_operation.c [hunk 3]
```diff
@@ -30,55 +30,85 @@ UCHAR
...
+        ULONG ReturnDataLength = 0;
         PREAD_CAPACITY16_DATA ReadCapacityData16 = DataBuffer;
-        REVERSE_BYTES_8(&ReadCapacityData16->LogicalBlockAddress, &BlockCount);
-        REVERSE_BYTES_8(&ReadCapacityData16->BytesPerBlock, &BlockSize);
-        if (CHECK_NBD_SEND_TRIM(Info->UserEntry->NbdFlags)) {
-            ReadCapacityData16->LBPME = 1;
+        REVERSE_BYTES_8(&ReadCapacityData16->LogicalBlockAddress, &maxLba);
+        REVERSE_BYTES_4(&ReadCapacityData16->BytesPerBlock, &BlockSize);
+
+        if (DataTransferLength >= (ULONG)FIELD_OFFSET(READ_CAPACITY16_DATA, Reserved3)) {
```
Comment (petrutlucian94) [inline driver/scsi_operation.c:90]: Supporting READ_CAPACITY_DATA_EX seems like a good idea.

File: driver/scsi_operation.c [hunk 4]
```diff
@@ -30,55 +30,85 @@ UCHAR
...
+            if (CHECK_NBD_SEND_TRIM(Info->UserEntry->NbdFlags)) {
```
Comment (petrutlucian94) [inline driver/scsi_operation.c:91]: This will have to be replaced with the following, as per recent changes:

`if (Info->UserEntry->Properties.Flags.UnmapSupported) {`

**Review by petrutlucian94 — CHANGES_REQUESTED** [review]
Looks good, thanks a lot for sending this fix! Could you please rebase the PR so that we can merge it?

File: driver/scsi_operation.c (hunk 3 above)
Comment (CzBiX) [reply driver/scsi_operation.c:90]: Yes, we have to support `READ_CAPACITY_DATA_EX`, the buffer size of system sizing request always not big enough to put `READ_CAPACITY16_DATA`.

**Comment by petrutlucian94** [comment]
@CzBiX one last thing before you rebase, can you please add a "Signed-off-by:" line to the commit message? I'm providing a contributor guide as we speak, similar to the Ceph one. That line will imply the license agreement.
